Stopcock Rate limit
Knawat/Knawat-NPM-JavaScript-SDK pull request #57
Opened 2020-12-03 09:54 UTC by dhavalsoni9989

- feature: Added the stopcock library for throttled the API limit

2020-12-03 15:36 UTC, HazemKhaled requested changes

2020-12-03 15:36 UTC, HazemKhaled commented on src/KnawatMP.js
> +  static stopcockRequest = stopcock(fetch, {
You forget to make `npm i stopcock --save`

2020-12-03 15:36 UTC, HazemKhaled commented on src/KnawatMP.js
> +    bucketSize: process.env.STOPCOCK_BUCKET_SIZE || 120,
use these number please
https://docs.knawat.io/#section/Knawat-API-rate-limit

2020-12-03 16:09 UTC, dhavalsoni9989 commented on src/KnawatMP.js
> +  static stopcockRequest = stopcock(fetch, {
@HazemKhaled 

I have added the stopcock in package.json file

2020-12-04 07:18 UTC, dhavalsoni9989 commented on src/KnawatMP.js
> +    bucketSize: process.env.STOPCOCK_BUCKET_SIZE || 120,
updated the code

2020-12-04 08:22 UTC, ismail9k commented
Form API using prospective, I think configuring the stopcock thought env variable is not the optimal solution, because they should not be constant across the app (unlike the base URL for example).
My proposed API using is passing the configs as the second argument, and giving the ability the disable throttling.

Passing no configs will be enabled by default
```js
 const mp = new MP({  store });
```

Updating only on value, the other values should go the defaults
```js
 const mp = new MP({  store }, { autoLimit: { bucketSize: 12 } });
```

Disable autoLimit
```js
 const mp = new MP({  store }, { autoLimit: false });
```

> P.S please update the readme file accordingly

2020-12-04 08:28 UTC, HazemKhaled requested changes

2020-12-04 08:28 UTC, HazemKhaled commented on src/KnawatMP.js
> +    interval: process.env.STOPCOCK_INTERVAL || 2000,
According to docs it should be 2/second
https://docs.knawat.io/#section/Knawat-API-rate-limit

2020-12-04 08:28 UTC, HazemKhaled commented on src/KnawatMP.js
> +    bucketSize: process.env.STOPCOCK_BUCKET_SIZE || 2,
bucketSize = 2! according to the Knawat docs, we don't watch the bucket size, so please update the docs or update the code here

2020-12-04 14:02 UTC, HazemKhaled requested changes

2020-12-04 14:02 UTC, HazemKhaled commented on README.md
> +  autoLimit: { bucketSize: 2, interval: 1000, limit: 1 },
autoLimit is optional, don't update all examples, just add one example in case we need to overwrite the values

2020-12-04 14:52 UTC, dhavalsoni9989 commented on README.md
> +  autoLimit: { bucketSize: 2, interval: 1000, limit: 1 },
Updated the code

2020-12-04 14:53 UTC, dhavalsoni9989 commented on src/KnawatMP.js
> +    bucketSize: process.env.STOPCOCK_BUCKET_SIZE || 2,
Added the unit test cases and updated the code

2020-12-11 06:11 UTC, ismail9k commented on src/KnawatMP.js
> +    this.autoLimit = autoLimit || {};
This will break if I passed `autoLimit: false`

2020-12-11 06:11 UTC, ismail9k commented on src/KnawatMP.js
> +    if (this.autoLimit) {
`autoLimit` will always be true

2020-12-11 08:30 UTC, HazemKhaled commented on src/KnawatMP.js
> +    this.autoLimit = autoLimit || {};
You shouldn't disable it, MP will fail your requests if you ignore it

2020-12-11 08:35 UTC, HazemKhaled commented on src/KnawatMP.js
> +    this.autoLimit = autoLimit || {};
But you can create an instance with apiRateLimit.limit = 99

but you will get this error ;)
![image](https://user-images.githubusercontent.com/125433/101881084-f968c380-3ba4-11eb-88da-35c4b870bbc5.png)

2020-12-11 10:38 UTC, ismail9k approved these changes

2020-12-11 10:39 UTC, merged